# Generated by Django 3.1.4 on 2021-01-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='isMale',
        ),
        migrations.RemoveField(
            model_name='post',
            name='modifyDate',
        ),
        migrations.AlterField(
            model_name='post',
            name='pubDate',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
