# Generated by Django 3.1.4 on 2021-01-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
